version: "3"
services:
  reservations-notifications-app:
    build:
      context: .
      args:
        - env=DEV
    ports:
      - "3008:3008"
    volumes:
      - .:/usr/src/app
    networks:
      - microservices-network

networks:
  microservices-network:
    external:
      name: 211150-211064-186499-back_microservices-network

