name: Tests

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - develop
      - main

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install modules
        run: npm ci

      - name: Run tests
        run: npm test
